-- coc.lua

--return {
--  -- Install coc.nvim for diagnostics and linting
--  {
--    "neoclide/coc.nvim",
--    branch = "release",
--    config = function()
--      -- CoC Configuration: LaTeX extensions
--      vim.g.coc_global_extensions = {
--        "coc-texlab", -- Use texlab for LaTeX support
--        "coc-json", -- JSON support
--        "coc-snippets", -- Snippets support
--      }
--
--      -- Configure CoC to use texlab (LaTeX language server)
--      vim.g.coc_user_config = {
--        languageserver = {
--          latex = {
--            command = "texlab", -- Using texlab for LaTeX LSP
--            filetypes = { "tex", "bib" }, -- LaTeX and bibtex filetypes
--            rootPatterns = { "latexmkrc", ".latexmkrc", ".git" }, -- Root detection
--            settings = {
--              texlab = {
--                build = {
--                  executable = "latexmk",
--                  args = { "-pdf", "%f" },
--                },
--                diagnostics = {
--                  onSave = false, -- Disable diagnostics on save
--                  onType = true, -- Enable diagnostics as you type
--                },
--              },
--            },
--          },
--        },
--
--        -- Enable chktex for diagnostics and linting
--        diagnostics = {
--          enable = true,
--          chktex = {
--            enable = true, -- Enable chktex diagnostics
--            command = "/usr/bin/chktex", -- Specify path to chktex if necessary
--            args = { "-v0", "-I0" }, -- Custom arguments for chktex
--            onType = true, -- Enable chktex linting as you type
--          },
--        },
--      }
--    end,
--  },
--}
