--return {
--  {
--    "lervag/vimtex",
--    config = function()
--      -- Configure vimtex
--      vim.g.vimtex_view_method = "zathura" -- Customize this to your PDF viewer (e.g., 'zathura', 'sumatrapdf')
--      vim.g.vimtex_quickfix_mode = 0 -- Disable quickfix
--      vim.g.vimtex_compiler_method = "latexmk" -- Use latexmk for compilation
--      vim.g.vimtex_compiler_latexmk = {
--        executable = "latexmk", -- Ensure latexmk is in your $PATH
--        options = { "-pdf", "-silent" }, -- Customize latexmk options if needed
--      }
--    end,
--  },
--}
